apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "faktory.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "faktory.name" . }}
    helm.sh/chart: {{ include "faktory.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # if upgrading with license, this does not work
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
{{- if not .Values.passwordExistingSecret }}
  password: {{ include "faktory.password" . | b64enc | quote }}
{{- end -}}
{{- if .Values.license }}
  license: {{ .Values.license | b64enc | quote }}
{{- end }}
